# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 791, 601))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(349, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setGeometry(QtCore.QRect(302, 80, 201, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 130, 201, 21))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(290, 180, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.registerlink = QtWidgets.QCommandLinkButton(self.page)
        self.registerlink.setGeometry(QtCore.QRect(410, 180, 193, 41))
        self.registerlink.setObjectName("registerlink")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.travelbox = QtWidgets.QCheckBox(self.page_2)
        self.travelbox.setGeometry(QtCore.QRect(280, 370, 87, 20))
        self.travelbox.setObjectName("travelbox")
        self.femalebtn = QtWidgets.QRadioButton(self.page_2)
        self.femalebtn.setGeometry(QtCore.QRect(420, 280, 100, 20))
        self.femalebtn.setObjectName("femalebtn")
        self.registerbtn = QtWidgets.QPushButton(self.page_2)
        self.registerbtn.setGeometry(QtCore.QRect(350, 430, 113, 32))
        self.registerbtn.setObjectName("registerbtn")
        self.countrieslist = QtWidgets.QComboBox(self.page_2)
        self.countrieslist.setGeometry(QtCore.QRect(320, 200, 171, 26))
        self.countrieslist.setObjectName("countrieslist")
        self.malebtn = QtWidgets.QRadioButton(self.page_2)
        self.malebtn.setGeometry(QtCore.QRect(310, 280, 100, 20))
        self.malebtn.setObjectName("malebtn")
        self.shoppingbox = QtWidgets.QCheckBox(self.page_2)
        self.shoppingbox.setGeometry(QtCore.QRect(380, 370, 87, 20))
        self.shoppingbox.setObjectName("shoppingbox")
        self.passwordfield = QtWidgets.QLineEdit(self.page_2)
        self.passwordfield.setGeometry(QtCore.QRect(292, 120, 241, 21))
        self.passwordfield.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordfield.setObjectName("passwordfield")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(330, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(370, 250, 60, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(370, 170, 60, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(360, 330, 81, 16))
        self.label_8.setObjectName("label_8")
        self.usernamefield = QtWidgets.QLineEdit(self.page_2)
        self.usernamefield.setGeometry(QtCore.QRect(292, 70, 241, 21))
        self.usernamefield.setObjectName("usernamefield")
        self.sportsbox = QtWidgets.QCheckBox(self.page_2)
        self.sportsbox.setGeometry(QtCore.QRect(490, 370, 87, 20))
        self.sportsbox.setObjectName("sportsbox")
        self.backlink = QtWidgets.QCommandLinkButton(self.page_2)
        self.backlink.setGeometry(QtCore.QRect(480, 430, 193, 41))
        self.backlink.setObjectName("backlink")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.registerlink.clicked.connect(MainWindow.onnavtoregister)
        self.backlink.clicked.connect(MainWindow.onnavtologin)
        self.registerbtn.clicked.connect(MainWindow.onregister)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Login Here"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Username"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter Password"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.registerlink.setText(_translate("MainWindow", "Register Here"))
        self.travelbox.setText(_translate("MainWindow", "Travel"))
        self.femalebtn.setText(_translate("MainWindow", "Female"))
        self.registerbtn.setText(_translate("MainWindow", "Register"))
        self.malebtn.setText(_translate("MainWindow", "Male"))
        self.shoppingbox.setText(_translate("MainWindow", "Shopping"))
        self.passwordfield.setPlaceholderText(_translate("MainWindow", "Enter Password"))
        self.label_5.setText(_translate("MainWindow", "Register Here!"))
        self.label_6.setText(_translate("MainWindow", "Gender"))
        self.label_7.setText(_translate("MainWindow", "Country"))
        self.label_8.setText(_translate("MainWindow", "Preferences"))
        self.usernamefield.setPlaceholderText(_translate("MainWindow", "Enter Username"))
        self.sportsbox.setText(_translate("MainWindow", "Sports"))
        self.backlink.setText(_translate("MainWindow", "Back"))

